- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Download wireguard Installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/l-n-s/wireguard-install/master/wireguard-install.sh
        dest: /opt/wireguard.sh
        mode: '0755'
    - name: Install Wireguard with client
      shell: /opt/wireguard.sh
      environment:
        DEBIAN_FRONTEND: "noninteractive"
        CLIENT_DNS: "1"
        CLIENT_NAME: "test"
        INTERACTIVE: "no"
      register: qrcode
    - debug: var=qrcode